# Generated by Django 5.0.6 on 2024-07-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='backgrounda.jpg', null=True, upload_to='static/images/'),
        ),
    ]
