# Generated by Django 5.0.6 on 2024-07-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0012_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='static/images/profile_pictures/background.jpg', null=True, upload_to='static/images/profile_pictures'),
        ),
    ]
