# Generated by Django 5.0.6 on 2024-08-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0013_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceamount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
